# Generated by Django 3.1.6 on 2021-02-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solution',
            new_name='Post',
        ),
    ]
